version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - sample-java-library-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
            - ~/code/.gradle
          key: sample-java-library-{{ checksum "build.gradle" }}

  build_and_upload:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - sample-java-library-{{ checksum "build.gradle" }}
      - run: git describe --tags
      - run: ./gradlew build bintrayUpload
      - save_cache:
          paths:
            - ~/.gradle
            - ~/code/.gradle
          key: sample-java-library-{{ checksum "build.gradle" }}

workflows:
  version: 2
  untagged_build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  tagged_build:
    jobs:
      - build_and_upload:
          filters:
            tags:
              only: /.*/
