/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.plavjanik.sample;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        assertEquals(1.0, Library.summaryStatistics(0.0, 1.0, 2.0).getMean(), 0.0);
    }
}
