/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.plavjanik.sample;

import org.apache.commons.math3.stat.descriptive.StatisticalSummary;
import org.apache.commons.math3.stat.descriptive.SummaryStatistics;

/**
 * Sample library with a statistical function.
 * <p>
 * <b>Example:</b>
 * <pre>
 * <code>
 * import net.plavjanik.sample.Library;
 *
 * Library.summaryStatistics(0.0, 1.0, 2.0).getMean();  // returns 1.0
 * </code>
 * </pre>
 */
public class Library {
    private Library() {
        // prevent instances being created
    }

    /**
     * Computes univariate statistical summary ({@link StatisticalSummary}) for
     * parameters used to call this method.
     *
     * @param values Values for the computation.
     * @return Return a {@link StatisticalSummary} instance reporting current
     *         statistics.
     */
    public static StatisticalSummary summaryStatistics(double... values) {
        SummaryStatistics stats = new SummaryStatistics();
        for (double value : values) {
            stats.addValue(value);
        }
        return stats.getSummary();
    }
}
